varnames = {'T','PIF4m','PIF5m','PIF','phyB','PR','INT','IAA29m','ATHB2m','CDF1m',...
    'FKF1m','FKF1','CDF1','COm','CO','FTm','InducedC1','InducedC2','RepressedC1',...
    'PHYAm','phyAr','phyAfr','phyAmarker'};

save('varnames','varnames')